name: CI para postulacion de QA Automation

on: 
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    run-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout a repositorio
              uses: actions/checkout@v3

            - name: Insatalar java JDK 17
              uses: actions/setup-java@v3
              with:
                java-version: '17'

            - name: Construir proyecto
              run: mvn clean install -DskipTests
            
            - name: Ejecutar pruebas
              run: mvn test

            - name: Subir reporte de pruebas
              if: always()
              uses: actions/upload-artifact@v4
              with:
                name: TestReport
                path: results/
